<?php

use Drupal\Core\Url;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_theme().
 */
function content_entity_example_theme() {
  return [
    'content_entity_example' => [
      'render element' => 'elements',
      'template' => 'views-view-fields--persons',
    ],
  ];
}

/**
 * Prepares variables for sponsor templates.
 */
function template_preprocess_content_entity_example(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
