<?php
///*
//* @file
//* code for select from bd module
//* @file
//* Contains mymodule.module.
//*/
//
//use Drupal\Core\Form\FormStateInterface;
///**
// * Implements hook_form_FORM_ID_alter() on behalf of mymodule.module.
// * @see \Array method Array at Array
// */
//function my_join_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//    if ($form_id == 'user_register_form') {
//      $form['#theme'] = 'user-registe-form';
////        kint($form_state);
//        $form['actions']['submit']['#submit'][] = 'my_join_user_register_submit';
//        $form['firstname'] = array(
//            '#type' => 'textfield',
//            '#title' => t('First name'),
//            '#required' => true,
//        );
//        $form['lastname'] = array(
//            '#type' => 'textfield',
//            '#title' => t('Last name'),
//            '#required' => true,
//        );
//        $form['password'] = array(
//            '#type' => 'password',
//            '#title' => t('Password'),
//            '#required' => true,
//        );
//        $form['confirm'] = array(
//            '#type' => 'textfield',
//            '#title' => t('Confirm'),
//            '#required' => true,
//        );
//        $form['brdate'] = array(
//            '#type' => 'date',
//            '#title' => t('Birth day'),
//            '#date_date_format' => 'd-m-Y',
//            '#required' => true,
//        );
//        return $form;
//    }
////    drupal_set_message('my_join_form_user_register_form_alter() executed.');
//}
//function my_join_user_register_submit($form, \Drupal\Core\Form\FormStateInterface $form_state){
//    $fname = $form_state->getValue('firstname');
//    $sname = $form_state->getValue('lastname');
//    $date = $form_state->getValue('brdate');
//
//    $mail = $form_state->getValue('mail');
//    $name = $form_state->getValue('name');
//    $pass = $form_state->getValue('password');
//
//    $form_state->setValue('field_first_name', $fname);
//    $form_state->setValue('field_last_name', $sname);
//    $form_state->setValue('field_birth_day', $date);
//    $form_state->setValue('status', 1);
//
//    kint($form_state);
//    die();
//}