<?php

/**
 * hook_preprocess_views_view().
 */
function slider_preprocess_node(&$variables)
{
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
        // You can get nid and anything else you need from the node object.
        $nid = $node->id();

    }
    if (isset($nid)) {
        if ($nid == 10) {
            $variables['#attached']['library'][] = 'slider/slick';
        }
    }
}